version: '2'

services:

  mysql-container:
    image: mysql:8.0
    container_name: mysql-docker-container
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: internship
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  internship-container:
    image: internship:latest
    container_name: interhsip
    depends_on:
      - mysql-container
    ports:
      - 8080:8080
    environment:
      DATABASE_HOST: mysql-container
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: internship4
      DATABASE_PORT: 3306